#!/usr/bin/env python3
"""Generate the RenderGraph API reference (Markdown) from Doxygen XML.

Produces a single Markdown file grouped by header, listing every public
class/struct/enum, its documented members and enum values, plus the free
functions and type aliases declared in the RenderGraph headers.

Usage: gen_api_md.py <doxygen-xml-dir> <output.md>
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

API_COMPOUND_KINDS = {"class", "struct", "enum"}
GENERATOR_NOTE = (
    "<!-- Generated by docs/gen_api_md.py from the Doxygen comments in "
    "src/RenderGraph/*.h. Do not edit by hand. -->"
)


def _text(element: ET.Element | None) -> str:
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def _first_para(element: ET.Element | None) -> str:
    """Return the text of the first <para> (skipping parameter/return lists)."""
    if element is None:
        return ""
    para = element.find("para")
    if para is not None:
        return _text(para)
    return _text(element)


def _summary(brief_el: ET.Element | None, detailed_el: ET.Element | None) -> str:
    brief = _text(brief_el)
    if brief:
        return brief
    return _first_para(detailed_el)


def _section_members(compounddef: ET.Element, kinds: tuple[str, ...]):
    """Yield public memberdef elements from sections whose kind matches."""
    for section in compounddef.findall("sectiondef"):
        kind = section.get("kind") or ""
        if not (kind.startswith("public-") or kind in kinds):
            continue
        for member in section.findall("memberdef"):
            if member.get("prot") not in (None, "public"):
                continue
            yield kind, member


def _signature(member: ET.Element) -> str:
    kind = member.get("kind")
    name = member.findtext("name") or ""
    if kind == "function":
        definition = _text(member.find("definition"))
        args = _text(member.find("argsstring"))
        # `definition` already contains the qualified name; trim it for readability.
        if definition.endswith(name):
            definition = definition[: -len(name)]
        return f"{definition}{name}{args}".strip()
    type_text = _text(member.find("type"))
    return f"{type_text} {name}".strip()


def _description(member: ET.Element) -> str:
    return _summary(member.find("briefdescription"), member.find("detaileddescription"))


def _member_location_file(member: ET.Element) -> str:
    location = member.find("location")
    if location is None:
        return "Unknown"
    return os.path.basename(location.get("file") or "Unknown")


def _enum_values(compounddef: ET.Element) -> list[tuple[str, str]]:
    values: list[tuple[str, str]] = []
    for section in compounddef.findall("sectiondef"):
        if section.get("kind") != "enumvalue":
            continue
        for member in section.findall("memberdef"):
            name = member.findtext("name") or ""
            values.append((name, _description(member)))
    return values


def _location_file(compounddef: ET.Element) -> str:
    location = compounddef.find("location")
    if location is None:
        return "Unknown"
    return os.path.basename(location.get("file") or "Unknown")


def _kind_label(kind: str) -> str:
    return {"class": "class", "struct": "struct", "enum": "enum"}.get(kind, kind)


def collect(xml_dir: str):
    """Return {header: [entries sorted by name]}."""
    index = ET.parse(os.path.join(xml_dir, "index.xml")).getroot()
    by_header: dict[str, list[dict]] = {}

    for compound in index.findall("compound"):
        kind = compound.get("kind")
        refid = compound.get("refid") or ""
        path = os.path.join(xml_dir, f"{refid}.xml")
        if not os.path.isfile(path):
            continue
        compounddef = ET.parse(path).getroot().find("compounddef")
        if compounddef is None or compounddef.get("prot") not in (None, "public"):
            continue

        name = compounddef.findtext("compoundname") or compound.get("name") or ""
        brief = _summary(compounddef.find("briefdescription"), compounddef.find("detaileddescription"))
        header = _location_file(compounddef)

        if kind == "namespace":
            # Free functions / typedefs / enums live in the namespace compound; the enums are
            # indexed separately, so only surface functions, variables and typedefs here. Each
            # member is grouped under the header that actually declares it.
            for section_kind, member in _section_members(compounddef, ("func", "var", "typedef", "enum")):
                member_header = _member_location_file(member)
                values = []
                if section_kind == "enum":
                    for enum_value in member.findall("enumvalue"):
                        values.append((enum_value.findtext("name") or "", _description(enum_value)))
                by_header.setdefault(member_header, []).append(
                    {
                        "sort": name + "::" + (member.findtext("name") or ""),
                        "namespace": name,
                        "kind": "function" if section_kind == "func" else section_kind,
                        "name": member.findtext("name") or "",
                        "brief": _description(member),
                        "signature": _signature(member),
                        "values": values,
                    }
                )
            continue

        if kind not in API_COMPOUND_KINDS:
            continue

        entry = {
            "sort": name,
            "namespace": "",
            "kind": kind,
            "qualified": name,
            "brief": brief,
            "members": [],
            "values": _enum_values(compounddef) if kind == "enum" else [],
        }
        scope = name + "::"
        for section_kind, member in _section_members(compounddef, ("enumvalue",)):
            if section_kind == "enumvalue":
                continue
            # Drop the owning class qualification so the table stays readable.
            entry["members"].append(
                {
                    "kind": member.get("kind"),
                    "name": member.findtext("name") or "",
                    "brief": _description(member),
                    "signature": _signature(member).replace(scope, ""),
                }
            )
        by_header.setdefault(header, []).append(entry)

    for entries in by_header.values():
        entries.sort(key=lambda e: e["sort"])
    return by_header


def render(by_header: dict[str, list[dict]]) -> str:
    lines: list[str] = [
        GENERATOR_NOTE,
        "",
        "# RenderGraph API reference",
        "",
        "Auto-generated from the Doxygen comments in `src/RenderGraph/*.h`. "
        "See [RenderGraph.md](RenderGraph.md) for the conceptual overview.",
        "",
        "Coverage is enforced: `docs/check_api_coverage.py` fails the build when a "
        "public entity is undocumented.",
        "",
    ]

    for header in sorted(by_header):
        lines.append(f"## `{header}`")
        lines.append("")
        for entry in by_header[header]:
            if "qualified" in entry:
                lines.append(f"### `{_kind_label(entry['kind'])} {entry['qualified']}`")
            elif entry.get("kind") == "enum":
                lines.append(f"### `enum {entry['name']}`")
            else:
                lines.append(f"### `{entry['signature']}`")
            lines.append("")
            if entry.get("brief"):
                lines.append(entry["brief"])
                lines.append("")
            if entry.get("values"):
                lines.append("| Value | Description |")
                lines.append("| --- | --- |")
                for name, desc in entry["values"]:
                    lines.append(f"| `{name}` | {desc or ''} |")
                lines.append("")
            if entry.get("members"):
                lines.append("| Member | Description |")
                lines.append("| --- | --- |")
                for member in entry["members"]:
                    signature = member["signature"].replace("|", "\\|")
                    lines.append(f"| `{signature}` | {member['brief'] or ''} |")
                lines.append("")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2
    by_header = collect(argv[1])
    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write(render(by_header))
    total = sum(len(v) for v in by_header.values())
    print(f"Wrote {argv[2]} ({total} entities across {len(by_header)} headers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
