name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Submodule Checkout
      uses: jwsi/submodule-checkout@v1

    - name: Install Vulkan
      run: wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.135-bionic.list http://packages.lunarg.com/vulkan/1.2.135/lunarg-vulkan-1.2.135-bionic.list && sudo apt update && sudo apt install vulkan-sdk
    - name: Install Dependencies
      run: sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev
    - name: configure
      run: cmake .
    - name: make
      run: make
