name: Windows

on: [push]

jobs:
  build_windows_2016:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v2
    - name: Submodule Checkout
      run: git submodule update --init
    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v1
      with:
          path: "C:\\VulkanSDK\\1.2.176.1"
          key: vulkan-sdk-1.2.176.1
    - name: Install Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.176.1/windows/VulkanSDK-1.2.176.1-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
    - name: configure default
      run: cmake .
    - name: build
      run: cmake --build .
    - name: configure Ray Tracing
      run: cmake . -DFEATURE_RAY_TRACING=on
    - name: build Ray Tracing
      run: cmake --build .
